### PR TITLE
Deviation

### PR DESCRIPTION
**Pull request by jhollist**
I'm submitting this, but I think there is a bug with turf.js

Examples on the site and with this function do not return the correct standard deviation value.

On the R side I am using the same example data that turf.js shows for [aggregate](http://turfjs.org/static/docs/module-turf_aggregate.html).  Scroll down in the results of the example, they report a sd of 216.025 and var of 46666.67 for 200, 600, 100.  The correct variance is 70000 and sd is 264.57.

I'm going to submit an issue.  Feel free to hold on this PR @sckott until they get it resolved.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @jhollist - sounds good. I'll wait a bit

**Comment by jhollist** [comment]
Cool.  Issue submitted over at https://github.com/Turfjs/turf/issues/246

**Comment by jhollist** [comment]
Heard back on the turf.js issue.  It is calculating the population sd, not the sample sd.  I should have figured this out, but to be honest I have only ever used the sample sd.  IMO, that is probably what turf.js should use, but it doesn't... 

I updated the documentation on deviation.R to indicate that it calcs population sd.  I think this should be sufficient at this point.  

I thought about adding a toggle to return either, but thought it best to stick with what turf.js returns by defualt.

**Comment by sckott** [comment]
okay, sounds good @jhollist - merging

**Pull request merged**
