### PR TITLE
Fix readme images #62

### PR DESCRIPTION
**Pull request by BlancEleven**
#62 
I changed the images from their local addresses to their full URLs. 

*First time contributing to a project.

### CODE REVIEW

**Comment by sckott** [comment]
thanks @BlancEleven !!

this is great, except can you do it differently? 

There's this bit in issue #62 

> If the images are also used for vignettes or Rd files, you can put them
in the 'vignettes' or 'man/figures' directories. Otherwise, please put
them in the top-level 'tools' directory, or a subdirectory of it.

so I'd like those two images in a new directory `tools` in the root of the package - then change the links to that location - and relative links - not the full links

thanks!

**Comment by sckott** [comment]
you can just add commits to this pull request - and change back the current changes

**Comment by BlancEleven** [comment]
@sckott I created the new directory in the root of the project and changed the links on the readme files.

My apologies for the misunderstanding, sometimes Thursdays feel like Mondays around here.

**Comment by sckott** [comment]
thanks very much @BlancEleven looks good

**Pull request merged**
